# Generated by Django 5.2.5 on 2025-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('address_number', models.TextField()),
                ('address_street', models.TextField()),
                ('address_apt_number', models.TextField()),
                ('address_zip', models.TextField()),
                ('dob', models.DateTimeField()),
                ('date_registered', models.DateTimeField()),
                ('party', models.CharField(max_length=2)),
                ('precinct', models.IntegerField()),
                ('v20state', models.BooleanField()),
                ('v21town', models.BooleanField()),
                ('v21primary', models.BooleanField()),
                ('v22general', models.BooleanField()),
                ('v23town', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
