# Generated by Django 5.2.5 on 2025-11-27 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('profile_image_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promptmix_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subject', models.TextField()),
                ('text', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promptmix.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('follower_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promptmix.profile')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promptmix.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promptmix.profile')),
                ('prompt', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='boosted_prompt', to='promptmix.prompt')),
                ('remix', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='boosted_remix', to='promptmix.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Remix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promptmix.profile')),
                ('prompt', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='remixed_prompt', to='promptmix.prompt')),
                ('remix', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='remixed_remix', to='promptmix.prompt')),
            ],
        ),
    ]
