# Generated by Django 5.2.5 on 2025-11-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promptmix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
