# Generated by Django 5.2.5 on 2025-11-27 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptmix', '0003_alter_boost_prompt_alter_boost_remix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='remix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boosted_remix', to='promptmix.remix'),
        ),
        migrations.AlterField(
            model_name='remix',
            name='remix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remixed_remix', to='promptmix.remix'),
        ),
    ]
