# Generated by Django 5.2.5 on 2025-11-28 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptmix', '0004_alter_boost_remix_alter_remix_remix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remix',
            name='remix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_remix', to='promptmix.remix'),
        ),
    ]
